name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: read
    outputs:
      should_release: ${{ steps.verify-ci-status.outputs.result == 'success' && steps.interesting-categories.outputs.interesting == 'true' }}
    steps:
      - name: Verify CI status
        uses: jenkins-infra/verify-ci-status-action@v1.2.0
        id: verify-ci-status
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          output_result: true

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.19.0
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check interesting categories
        uses: jenkins-infra/interesting-category-action@v1.0.0
        id: interesting-categories
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-20.04
    needs: [validate]
    if: needs.validate.outputs.should_release == 'true'
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v3.1.1
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Release
        uses: jenkins-infra/jenkins-maven-cd-action@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
